### ISSUE TITLE
Create a debug output system

### ISSUE THREAD

**Issue by agathazeren** [asa-z/cuneiforbits#15]
Some way to log this for debugging and view in real time from a second terminal.

**Comment by yvnat** [comment]
A very easy (but also very messy) of doing this would be to have a "debug log" string, and reprint it below (or above) everything else whenever the screen is cleared and updated. Otherwise, I don't know anything about handling multiple terminals except for the fact that it can be very difficult on windows.

**Comment by agathazeren** [comment]
Yes, that is one option. In terms of multiple terminals it wouldn't be hard, except that you'd have to do IPC, and write a totally separate debugger program. 
But then you could also have a more sophisticated debugger. unless maybe we hijack some of the game controls. We could do that in `main`, which would be relatively minimally invasive.

**Comment by agathazeren** [comment]
Think that I will implement that idea.
